;RECEPTION CYCLIC BUFFER. INFORMATION IS TRANSMITTED THROUGH TX AND THEN RECEIVED THROUGH RX. THE INFORMATION IS GENERATED THROUGH DIPSW IN P1
;SHOW THE LAST CHARACTER RECEIVED AND THE NUMBER OF CHARS IN THE BUFFER IN PORTS P0 AND P2
;P3.1(TxD) IS CONNECTED TO P3.0(RxD)
	ORG	0000H
	LJMP	INIT

INIT:
	MOV	SCON, #50H
	MOV	TMOD, #20H
	MOV	TH1, #252
	MOV	R7, #00H	; COUNTER
	MOV	R0, #30H	; BUFFER START
	SETB	TR1

MAIN:
	ACALL	READ_PORT
	ACALL	TRANSMIT_BYTE
	ACALL	RECEIVE_BYTE
	ACALL	UPDATE_BUFFER
	ACALL	DISPLAY_DATA
	SJMP	MAIN

READ_PORT:
	MOV	A, P1
	RET

TRANSMIT_BYTE:
	MOV	SBUF, A
	JNB	TI, $
	CLR	TI
	RET

RECEIVE_BYTE:
	JNB	RI, $
	CLR	RI
	MOV	A, SBUF
	RET

UPDATE_BUFFER:
	MOV	@R0, A
	INC	R0
	INC	R7
	CJNE	R0, #38, NO_WRAP
	MOV	R0, #30
NO_WRAP:
	CJNE	R7, #09, NO_OVERFLOW
	DEC	R7
NO_OVERFLOW:
	RET

DISPLAY_DATA:
	MOV	P0, A		;DISPLAY LAST CHAR RECEIVED
	MOV	P2, R7		;DISPLAY COUNTER
	RET

	END

