; DATA RECEPTION THROUGH RX UNTIL char not received for >5ms, ON 7SEGMENT HEX DISPLAY IN PORT 1 DISPLAY THE CHARACTER BEING RECEIVED, IN P2 THE NUMBER OF CHAR RECEIVED

	ORG	0000H
	LJMP	INIT
	ORG	000BH
	LJMP	ENDI

INIT:
	MOV	R0, #00H	; COUNTER
	MOV	SCON, #50H
	MOV	TMOD, #21H
	MOV	TH1, #252
	MOV	TH0, #0EAH	; LOAD 65K - 5K FOR 5MS TIMER
	MOV	TL0, #79H
	SETB	EA
	SETB	ET0
	SETB	TR1
MAIN:
	ACALL	RECEIVE_CHAR
	ACALL	DISPLAY_CHAR
	ACALL	DISPLAY_COUNTER
	SJMP	MAIN

RECEIVE_CHAR:
	SETB	TR0
	JNB	RI, $
	CLR	TR0
	MOV	TH0, #0EAH
	MOV	TL0, #79H
	CLR	RI
	INC	R0
	MOV	A, SBUF
	RET

DISPLAY_CHAR:
	MOV	P1, A
	RET
DISPLAY_COUNTER:
	MOV	P2, R0
	RET

ENDI:	END

