; DATA RECEPTION THROUGH RX UNTILL CR+LF, ON 7SEGMENT HEX DISPLAY IN PORT 1 DISPLAY THE CHARACTER BEING RECEIVED, IN P2 THE NUMBER OF CHAR RECEIVED

	ORG	0000H
	LJMP	INIT

INIT:
	MOV	R0, #00H	; COUNTER
	MOV	SCON, #50H
	MOV	TMOD, #20H
	MOV	TH1, #252
	SETB	TR1
MAIN:
	ACALL	RECEIVE_CHAR
	ACALL	DISPLAY_CHAR
	ACALL	DISPLAY_COUNTER
	SJMP	MAIN

RECEIVE_CHAR:
	JNB	RI, $
	CLR	RI
	INC	R0
	MOV	A, SBUF
	CJNE	A, #0DH, RECEIVE_CHAR
	JNB	RI, $
	CLR	RI
	MOV	A, SBUF
	CJNE	A, #0AH, RECEIVE_CHAR
	SJMP	ENDI

	RET

DISPLAY_CHAR:
	MOV	P1, A
	RET
DISPLAY_COUNTER:
	MOV	P2, R0
	RET

ENDI:	END
